language: objective-c
podfile: Example/Podfile
osx_image: xcode9.1
rvm:
  - 2.2.2
before_install:
- gem install cocoapods xcpretty --no-ri --no-rdoc
- travis_wait pod repo update --silent
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/CentrifugeiOS.xcworkspace -scheme CentrifugeiOS-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.0,name=iPhone SE' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
